<?php

namespace App;

class Deck {
	const DECK = [
		array('rank' => 2, 'face' => '2', 'suit' => 'C'),
		array('rank' => 3, 'face' => '3', 'suit' => 'C'),
		array('rank' => 4, 'face' => '4', 'suit' => 'C'),
		array('rank' => 5, 'face' => '5', 'suit' => 'C'),
		array('rank' => 6, 'face' => '6', 'suit' => 'C'),
		array('rank' => 7, 'face' => '7', 'suit' => 'C'),
		array('rank' => 8, 'face' => '8', 'suit' => 'C'),
		array('rank' => 9, 'face' => '9', 'suit' => 'C'),
		array('rank' => 10, 'face' => 'T', 'suit' => 'C'),
		array('rank' => 11, 'face' => 'J', 'suit' => 'C'),
		array('rank' => 12, 'face' => 'Q', 'suit' => 'C'),
		array('rank' => 13, 'face' => 'K', 'suit' => 'C'),
		array('rank' => 14, 'face' => 'A', 'suit' => 'C'),
		array('rank' => 2, 'face' => '2', 'suit' => 'D'),
		array('rank' => 3, 'face' => '3', 'suit' => 'D'),
		array('rank' => 4, 'face' => '4', 'suit' => 'D'),
		array('rank' => 5, 'face' => '5', 'suit' => 'D'),
		array('rank' => 6, 'face' => '6', 'suit' => 'D'),
		array('rank' => 7, 'face' => '7', 'suit' => 'D'),
		array('rank' => 8, 'face' => '8', 'suit' => 'D'),
		array('rank' => 9, 'face' => '9', 'suit' => 'D'),
		array('rank' => 10, 'face' => 'T', 'suit' => 'D'),
		array('rank' => 11, 'face' => 'J', 'suit' => 'D'),
		array('rank' => 12, 'face' => 'Q', 'suit' => 'D'),
		array('rank' => 13, 'face' => 'K', 'suit' => 'D'),
		array('rank' => 14, 'face' => 'A', 'suit' => 'D'),
		array('rank' => 2, 'face' => '2', 'suit' => 'H'),
		array('rank' => 3, 'face' => '3', 'suit' => 'H'),
		array('rank' => 4, 'face' => '4', 'suit' => 'H'),
		array('rank' => 5, 'face' => '5', 'suit' => 'H'),
		array('rank' => 6, 'face' => '6', 'suit' => 'H'),
		array('rank' => 7, 'face' => '7', 'suit' => 'H'),
		array('rank' => 8, 'face' => '8', 'suit' => 'H'),
		array('rank' => 9, 'face' => '9', 'suit' => 'H'),
		array('rank' => 10, 'face' => 'T', 'suit' => 'H'),
		array('rank' => 11, 'face' => 'J', 'suit' => 'H'),
		array('rank' => 12, 'face' => 'Q', 'suit' => 'H'),
		array('rank' => 13, 'face' => 'K', 'suit' => 'H'),
		array('rank' => 14, 'face' => 'A', 'suit' => 'H'),
		array('rank' => 2, 'face' => '2', 'suit' => 'S'),
		array('rank' => 3, 'face' => '3', 'suit' => 'S'),
		array('rank' => 4, 'face' => '4', 'suit' => 'S'),
		array('rank' => 5, 'face' => '5', 'suit' => 'S'),
		array('rank' => 6, 'face' => '6', 'suit' => 'S'),
		array('rank' => 7, 'face' => '7', 'suit' => 'S'),
		array('rank' => 8, 'face' => '8', 'suit' => 'S'),
		array('rank' => 9, 'face' => '9', 'suit' => 'S'),
		array('rank' => 10, 'face' => 'T', 'suit' => 'S'),
		array('rank' => 11, 'face' => 'J', 'suit' => 'S'),
		array('rank' => 12, 'face' => 'Q', 'suit' => 'S'),
		array('rank' => 13, 'face' => 'K', 'suit' => 'S'),
		array('rank' => 14, 'face' => 'A', 'suit' => 'S')
	];

}